name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: dump context
      env:
        CONTEXT_CONTENTS: ${{toJson(github)}}
      run: echo "$CONTEXT_CONTENTS"

    - uses: weirdan/create-deployment-action@master
      id: deployment
      with:
        token: ${{github.token}}
        required_contexts: "[]"
        ref: ${{github.head_ref || github.ref }}
        auto_merge: false
        environment: staging
    - uses: ./
      with:
        token: ${{github.token}}
        deployment_id: ${{steps.deployment.outputs.deployment_id}}
        state: success
        log_url: "https://github.com/${{github.repository}}/runs/${{github.run_id}}"
        description: Successfully deployed to staging
        environment_url: https://staging.dev/
        auto_inactive: true
